### ISSUE TITLE
有个报错

### ISSUE THREAD

**Issue by chenxuuu** [zh-h/student-information-system-wechat-applet#2]
Do not have modalConfirm handler in current page: pages/index/index. Please make sure that modalConfirm handler has been defined in pages/index/index, or pages/index/index has been added into app.json
![qq 20170719175527](https://user-images.githubusercontent.com/10357394/28361474-7865cb46-6cab-11e7-91a6-08179aa745d6.png)

**Comment by zh-h** [comment]
@chenxuuu 我看了一下当前的小程序去掉了modal组件，而是直接用Javascript调用modal

https://mp.weixin.qq.com/debug/wxadoc/dev/framework/compatibility.html
```
wx.showModal({
  success: function(res) {
    if (wx.canIUse('showModal.cancel')) {
      console.log(res.cancel)
    }
  }
})
```

你现在的办法是把 https://github.com/zh-h/student-information-system-wechat-applet/blob/master/pages/index/index.wxml#L6-L8 
```
    <modal no-cancel="true" hidden="{{modalHidden}}" bindconfirm="modalConfirm" bindcancel="modalCancel">
        {{modalContent}}
    </modal>
```

两行去掉;
然后把 https://github.com/zh-h/student-information-system-wechat-applet/blob/master/pages/index/index.js#L89-L94
```
  showModal: function (msg) {
    this.setData({
      modalHidden: false,
      modalContent: msg
    })
  },
```
换成 https://mp.weixin.qq.com/debug/wxadoc/dev/api/api-react.html#wxshowmodalobject 类似的操作。
